import pytest
from unittest.mock import MagicMock
from core.autonomous_researcher import AutonomousResearcher
from core.goal_system import Goal, GoalMetricType

def test_autonomous_goal_synthesis():
    # Setup
    researcher = AutonomousResearcher()
    
    # Simulate an insight from DMN that identifies a low-coherence area
    class MockInsight:
        def __init__(self, description):
            self.description = description
            self.type = "heuristic"
    
    insights = [MockInsight("Found a low-coherence cluster in community 12")]
    
    # Execute goal synthesis
    synthesized_goal = researcher.synthesize_goals(insights)
    
    # Verify goal
    assert synthesized_goal is not None
    assert isinstance(synthesized_goal, Goal)
    assert synthesized_goal.autogenerated is True
    assert "low-coherence" in synthesized_goal.description.lower()
