apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cerebrum

resources:
  - namespace.yaml
  - pvc.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml

# Override image tag via: kustomize edit set image ghcr.io/brutalbyte/cerebrum:v2.58.0
images:
  - name: ghcr.io/brutalbyte/cerebrum
    newTag: latest
